#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.{build}.{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
#image: Visual Studio 2015

# clone directory
clone_folder: C:\projects\smoksmog-windows

# scripts that run after cloning repository
install:
- ps: >-
    "$($env:APPVEYOR_BUILD_FOLDER)\scripts\import-PfxCertificates.ps1"
    
    "$($env:APPVEYOR_BUILD_FOLDER)\scripts\install-dependencies.ps1"
    
#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration: Release

platform: x86
#  - Any CPU

build:
  project: SmokSmog.vs2015.sln
  parallel: true
  verbosity: minimal

before_build:
- ps: >-
    "$($env:APPVEYOR_BUILD_FOLDER)\.nuget\NuGet.exe" update -self > $null 2> $null

    "$($env:APPVEYOR_BUILD_FOLDER)\.nuget\NuGet.exe" restore > $null 2> $null

    "$($env:APPVEYOR_BUILD_FOLDER)\scripts\restore-assets.ps1" > $null 2> $null

#---------------------------------#
#       tests configuration       #
#---------------------------------#

after_test:
- ps: >-
    "$($env:APPVEYOR_BUILD_FOLDER)\scripts\codecov.ps1

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off