//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokSmog.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmokSmog.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmokSmog.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string StationSortModeEnumCity {
            get {
                return ResourceManager.GetString("StationSortModeEnumCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string StationSortModeEnumName {
            get {
                return ResourceManager.GetString("StationSortModeEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to province.
        /// </summary>
        public static string StationSortModeEnumProvince {
            get {
                return ResourceManager.GetString("StationSortModeEnumProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorites.
        /// </summary>
        public static string StringAddToFavorites {
            get {
                return ResourceManager.GetString("StringAddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air quality.
        /// </summary>
        public static string StringAirQuality {
            get {
                return ResourceManager.GetString("StringAirQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Quality Index.
        /// </summary>
        public static string StringAirQualityIndex {
            get {
                return ResourceManager.GetString("StringAirQualityIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string StringAverage {
            get {
                return ResourceManager.GetString("StringAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string StringBad {
            get {
                return ResourceManager.GetString("StringBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click RMB.
        /// </summary>
        public static string StringClickRMB {
            get {
                return ResourceManager.GetString("StringClickRMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string StringClose {
            get {
                return ResourceManager.GetString("StringClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string StringComponents {
            get {
                return ResourceManager.GetString("StringComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string StringErrorOccurred {
            get {
                return ResourceManager.GetString("StringErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string StringFavorites {
            get {
                return ResourceManager.GetString("StringFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find station.
        /// </summary>
        public static string StringFindStation {
            get {
                return ResourceManager.GetString("StringFindStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string StringFor {
            get {
                return ResourceManager.GetString("StringFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string StringGood {
            get {
                return ResourceManager.GetString("StringGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group by.
        /// </summary>
        public static string StringGroupBy {
            get {
                return ResourceManager.GetString("StringGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hold.
        /// </summary>
        public static string StringHold {
            get {
                return ResourceManager.GetString("StringHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string StringHomePage {
            get {
                return ResourceManager.GetString("StringHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home station.
        /// </summary>
        public static string StringHomeStation {
            get {
                return ResourceManager.GetString("StringHomeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        public static string StringInformation {
            get {
                return ResourceManager.GetString("StringInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string StringInitialization {
            get {
                return ResourceManager.GetString("StringInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legend.
        /// </summary>
        public static string StringLegend {
            get {
                return ResourceManager.GetString("StringLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizing canceled.
        /// </summary>
        public static string StringLocalizationCanceled {
            get {
                return ResourceManager.GetString("StringLocalizationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find device localization.
        /// </summary>
        public static string StringLocalizationNotFound {
            get {
                return ResourceManager.GetString("StringLocalizationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization is disabled in your device.
        /// </summary>
        public static string StringLocalizationOff {
            get {
                return ResourceManager.GetString("StringLocalizationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable localization and try again.
        /// </summary>
        public static string StringLocalizationTryAgain {
            get {
                return ResourceManager.GetString("StringLocalizationTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizing ....
        /// </summary>
        public static string StringLocalizing {
            get {
                return ResourceManager.GetString("StringLocalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string StringMap {
            get {
                return ResourceManager.GetString("StringMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string StringMeasure {
            get {
                return ResourceManager.GetString("StringMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string StringModerate {
            get {
                return ResourceManager.GetString("StringModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string StringNA {
            get {
                return ResourceManager.GetString("StringNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest stations.
        /// </summary>
        public static string StringNearestStations {
            get {
                return ResourceManager.GetString("StringNearestStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No API connection has been found.
        ///Please check your internet connection and try again later..
        /// </summary>
        public static string StringNoApiConnection {
            get {
                return ResourceManager.GetString("StringNoApiConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norm.
        /// </summary>
        public static string StringNorm {
            get {
                return ResourceManager.GetString("StringNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string StringNotAvailable {
            get {
                return ResourceManager.GetString("StringNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string StringNote {
            get {
                return ResourceManager.GetString("StringNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string StringOr {
            get {
                return ResourceManager.GetString("StringOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start.
        /// </summary>
        public static string StringPinToStart {
            get {
                return ResourceManager.GetString("StringPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string StringRemoveFromFavorites {
            get {
                return ResourceManager.GetString("StringRemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string StringRetry {
            get {
                return ResourceManager.GetString("StringRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string StringSearch {
            get {
                return ResourceManager.GetString("StringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string StringSelect {
            get {
                return ResourceManager.GetString("StringSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select from list.
        /// </summary>
        public static string StringSelectFromList {
            get {
                return ResourceManager.GetString("StringSelectFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as home station.
        /// </summary>
        public static string StringSetAsHomeStation {
            get {
                return ResourceManager.GetString("StringSetAsHomeStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string StringSettings {
            get {
                return ResourceManager.GetString("StringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow application to use GPS. 
        ///That allow you to find nearest stations..
        /// </summary>
        public static string StringSettingsLocalization {
            get {
                return ResourceManager.GetString("StringSettingsLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show home station statuses on primary live tile..
        /// </summary>
        public static string StringSettingsStringHomeStationLiveTile {
            get {
                return ResourceManager.GetString("StringSettingsStringHomeStationLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station list.
        /// </summary>
        public static string StringStationList {
            get {
                return ResourceManager.GetString("StringStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufficient.
        /// </summary>
        public static string StringSufficient {
            get {
                return ResourceManager.GetString("StringSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StringUnknown {
            get {
                return ResourceManager.GetString("StringUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string StringVersion {
            get {
                return ResourceManager.GetString("StringVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Bad.
        /// </summary>
        public static string StringVeryBad {
            get {
                return ResourceManager.GetString("StringVeryBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string StringVeryGood {
            get {
                return ResourceManager.GetString("StringVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to add your favorite station?.
        /// </summary>
        public static string StringWantToAddYourFavoriteStation {
            get {
                return ResourceManager.GetString("StringWantToAddYourFavoriteStation", resourceCulture);
            }
        }
    }
}
